---
title: De Kunstfabriek
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: luc.vandijck@duffel.be
description: Eindelijk een eigen website van de Kunstfabriek. Hier vind je info over
  de lessen. Laatste nieuws, zoals bijvoorbeeld over de "KUNSTROUTE". Ook informatie
  over de leraars en hoe je kan inschrijven.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
theme: minima
plugins:
- jekyll-feed
